### ISSUE TITLE
版本不一致

### ISSUE THREAD

**Issue by lsp10** [zjpjohn/ActiveMQTest#1]
@zjpjohn 这个demo中使用的版本和https://github.com/zjpjohn/ActiveMQ   不一致

**Comment by zjpjohn** [comment]
将activeMQ中的gav copy到ActiveMQTest中就可以了

**Comment by lsp10** [comment]
@zjpjohn 不行的我试过啦 你的包的名字都不一样  有一些类找不到

**Comment by zjpjohn** [comment]
这个项目测试公司的activeMQ  ，你只需要在spring配置文件加上activeMQ包扫描路径 就行了

**Comment by lsp10** [comment]
@zjpjohn 我已经运行起来啦    但是
java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392)
    at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:267)
    at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240)
    at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
    at java.lang.Thread.run(Thread.java:745)

**Comment by zjpjohn** [comment]
你的activeMQ broker 装了

**Comment by lsp10** [comment]
@zjpjohn   嗯嗯  偶尔会报这个错误       user的表你也没有给

**Comment by zjpjohn** [comment]
你可以更新下test代码   我把配置重新修改了下    在本地已经跑起来了

**Comment by lsp10** [comment]
@zjpjohn ```
  <groupId>com.qizhi.mq</groupId>
               <artifactId>activemq</artifactId>
              <version>5.8.0-RELEASE</version>

``` 这个版本和你发布的不一样
```

**Comment by zjpjohn** [comment]
应该是你把activeMQ broker关了吧

**Comment by zjpjohn** [comment]
代码是一样的

**Comment by zjpjohn** [comment]
java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:196)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at org.apache.activemq.transport.tcp.TcpBufferedInputStream.fill(TcpBufferedInputStream.java:50)
    at org.apache.activemq.transport.tcp.TcpTransport$2.fill(TcpTransport.java:634)
    at org.apache.activemq.transport.tcp.TcpBufferedInputStream.read(TcpBufferedInputStream.java:59)
    at org.apache.activemq.transport.tcp.TcpTransport$2.read(TcpTransport.java:619)
    at java.io.DataInputStream.readInt(DataInputStream.java:387)
    at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:267)
    at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240)
    at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232)
    at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
    at java.lang.Thread.run(Thread.java:745)
 WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.

**Comment by lsp10** [comment]
没有  现在运行起来啦    暂时没有发现问题

**Comment by zjpjohn** [comment]
你刚才是不是这个问题

**Comment by lsp10** [comment]
不是这个问题  那问题出现过两次  暂时还没有重现

**Comment by lsp10** [comment]
你把版本处理一下    就算下载下来也很难用的      更别提发现bug啦

**Comment by zjpjohn** [comment]
OK   已经提交了   我没想到会有人问我要测试例子   你是基于什么情况要使用消息队列的

**Comment by lsp10** [comment]
以前用的是redis做的   现在想全部用activeMq代替                解耦一个比较笨重的项目   做成分布式的SaaS平台

**Comment by lsp10** [comment]
你有好的HA方案吗

**Comment by zjpjohn** [comment]
你是指activeMQ的ha吗

**Comment by lsp10** [comment]
嗯嗯  是的  就是activeMQ

**Comment by zjpjohn** [comment]
每个节点配主备，再加上集群    既解决负载均衡 ，又解决因某个broker挂掉消息不能消费

**Comment by lsp10** [comment]
@zjpjohn   broker_url=failover:(tcp://192.168.211.134:61616,tcp://192.168.211.134:61626)

我想配置多个的broker  怎么不可以

**Comment by lsp10** [comment]
@zjpjohn   我也遇到这个问题啦
  你是怎么解决的

java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:196)
at java.net.SocketInputStream.read(SocketInputStream.java:122)
at org.apache.activemq.transport.tcp.TcpBufferedInputStream.fill(TcpBufferedInputStream.java:50)
at org.apache.activemq.transport.tcp.TcpTransport$2.fill(TcpTransport.java:634)
at org.apache.activemq.transport.tcp.TcpBufferedInputStream.read(TcpBufferedInputStream.java:59)
at org.apache.activemq.transport.tcp.TcpTransport$2.read(TcpTransport.java:619)
at java.io.DataInputStream.readInt(DataInputStream.java:387)
at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:267)
at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240)
at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232)
at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
at java.lang.Thread.run(Thread.java:745)
WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.
WARN | Failed to connect to [tcp://127.0.0.1:61616] after: 10 attempt(s) continuing to retry.

**Comment by zjpjohn** [comment]
你把 broker关了  或者是找不到broker的地址  这是activeMQ的重试机制

**Comment by zjpjohn** [comment]
是可以配多个的  你的多个broker是怎么配置的

**Comment by zjpjohn** [comment]
是静态配置 还是 动态的

**Comment by lsp10** [comment]
broker_url=failover:(tcp://192.168.211.134:61616,tcp://192.168.211.134:61626)  静态的  在配置文件中直接配置的

**Comment by zjpjohn** [comment]
把你的配置发出来看看

**Comment by lsp10** [comment]
@zjpjohn 
broker_url=failover:(tcp://192.168.211.134:61616,tcp://192.168.211.134:61626)
user_name= admin
password= admin
queue_name = user.message.queue.add
queue_name_2 = n2.message.queue.9

activeMq.xml
 <networkConnectors>
          <networkConnector uri="static:(tcp://127.0.0.1:61626)" duplex="true"/>
 </networkConnectors>

**Comment by zjpjohn** [comment]
亲  我说的静态配置是指 要配置broker

**Comment by zjpjohn** [comment]
网上关于activeMQ的配置 很多 可以参考的

**Comment by lsp10** [comment]
@zjpjohn 网上的例子都跑不通  你用的是什么方式？介绍一下呗

**Comment by gang-yu** [comment]
编译的时候说com.zjp.mq.annotation这个找不存在
